apiVersion: v1
kind: Service
metadata:
  name: src
  labels:
    app: src
spec:
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32001
  selector:
    app: src
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: src
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: src
    spec:
      containers:
        - name: src
          image: "127.0.0.1:30400/src:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000